# Generated by Django 5.1.2 on 2024-12-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='label',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing'), ('both', 'Both')], default='shipping', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
