# Generated by Django 5.1.2 on 2024-12-05 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, unique=True)),
                ('business_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=100)),
                ('store_name', models.CharField(max_length=255, unique=True)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_url', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Current verification status of the vendor', max_length=10, null=True)),
                ('account_status', models.CharField(blank=True, choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], default='pending', max_length=20, null=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('id_type', models.CharField(blank=True, max_length=15, null=True)),
                ('id_number', models.CharField(blank=True, max_length=15, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=15, null=True)),
                ('id_front_url', models.CharField(blank=True, max_length=255, null=True)),
                ('id_back_url', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('ship_from_address1', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_from_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_from_city', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_from_locality', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_from_region', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_from_country', models.CharField(blank=True, max_length=100, null=True)),
                ('return_address1', models.CharField(blank=True, max_length=255, null=True)),
                ('return_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('return_city', models.CharField(blank=True, max_length=100, null=True)),
                ('return_locality', models.CharField(blank=True, max_length=100, null=True)),
                ('return_region', models.CharField(blank=True, max_length=100, null=True)),
                ('return_country', models.CharField(blank=True, default='Ghana', max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('both', 'Both Bank Transfer and Mobile Money'), ('none', 'No Payment Method Set')], help_text='Select the payment method(s) you want to accept', max_length=20, null=True)),
                ('account_number', models.CharField(blank=True, help_text='Bank account number (required if payment type includes bank transfer)', max_length=100, null=True)),
                ('mobile_money_number', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('phone_number2', models.CharField(blank=True, max_length=16, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO-friendly title (max 70 characters)', max_length=70, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='SEO-friendly description (max 160 characters)', null=True)),
                ('meta_keywords', models.TextField(blank=True, help_text='Comma-separated keywords for SEO', null=True)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL for SEO', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store_name'], name='vendors_ven_store_n_ea5b94_idx'), models.Index(fields=['verification_status'], name='vendors_ven_verific_039b78_idx'), models.Index(fields=['account_status'], name='vendors_ven_account_020bb8_idx'), models.Index(fields=['payment_type'], name='vendors_ven_payment_e7fdbe_idx'), models.Index(fields=['ship_from_city'], name='vendors_ven_ship_fr_4431b6_idx'), models.Index(fields=['return_city'], name='vendors_ven_return__a24274_idx')],
            },
        ),
    ]
