# Generated by Django 5.1.2 on 2024-12-05 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=5, help_text='Unit price at the time added to cart', max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount on item', max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax on item', max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=1, help_text='(Price - Discount) * Quantity + Tax', max_digits=12)),
                ('is_available', models.BooleanField(default=True, help_text='Indicates if the item is still in stock')),
                ('is_wishlist_item', models.BooleanField(default=False, help_text='Indicates if the item is saved for later')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='cart.CartItem', to='products.product'),
        ),
    ]
