# Generated by Django 5.1.3 on 2024-12-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
    ]
