# Generated by Django 5.1.2 on 2024-12-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_convert_product_id_to_uuid'),
        ('products', '0006_alter_product_id'),
    ]

    operations = [
    ]
