# Generated by Django 5.1.3 on 2024-12-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_merge_20241217_1037'),
        ('products', '0008_switch_to_uuid'),
    ]

    operations = [
    ]
