# Generated by Django 5.1.3 on 2024-12-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_id_alter_productimage_product_and_more'),
    ]

    operations = [
    ]
