# Generated by Django 5.1.3 on 2024-12-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_id_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
