# Generated by Django 5.1.3 on 2024-12-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_productimage_options_alter_product_uuid'),
    ]

    operations = [
    ]
