# Generated by Django 5.1.2 on 2025-01-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_tag_options_tag_slug_tag_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uuid',
        ),
    ]
